version: '3.8'
services:
  cnosdb:
    image: cnosdb/cnosdb:v2.0.1
    container_name: cnosdb
    ports:
      - 31006:31006
      - 31007:31007
    environment:
      - cpu=2
      - memory=4
  emqx:
    image: emqx:latest
    container_name: emqx
    ports:
      - 18083:18083
      - 1883:1883
      - 8083:8083
      - 8084:8084
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ./etc/telegraf:/etc/telegraf
    command: /bin/bash -c "telegraf --config /etc/telegraf/telegraf.conf"
  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb
    ports:
      - 8086:8086
